name: vic_test_env
dependencies:
  - python=3.5
  - numpy
  - scipy
  - pytest
  - netCDF4
  - cffi
  - pandas
  - configobj
  - xarray
  - bottleneck
  - matplotlib
  - seaborn
  - psutil
>>>>>>> 0601cfc7ab8de2d5d50dae1d09e22a1774f5216a
  - pip:
    - git+https://github.com/UW-Hydro/tonic.git
    - engarde
    - pytest-faulthandler
    - pytest-xdist
    - gprof2dot
