#!/usr/bin/env python
from __future__ import print_function
import os
import stat
import shutil
try:
    from ConfigParser import SafeConfigParser
except ImportError:
    from configparser import SafeConfigParser

class VIC_Error(Exception):
    pass

# header to put above VIC style config files
header_template = '''# CESM-VIC Input File: {0}
# CASEID: {1}
'''

# CESM - VIC input file config
config_file = 'vic.inputfiles.cfg'


def main():

    # get CESM environment variables
    try:
        grid = os.environ['LND_GRID']
        casebld = os.environ['CASEBUILD']
        rundir = os.environ['RUNDIR']
        runtype = os.environ['RUN_TYPE']
        coderoot = os.environ['CODEROOT']
    except KeyError as e:
        print('KeyError was raised accessing CESM environment variables')
        raise(e)
    caseid = os.path.normpath(casebld).split(os.sep)[-2]

    # stop script if hybrid run is requested
    if runtype.lower() == 'hybrid':
        raise ValueError('Hybrid runs are not supported in RASM')

    # create vicconf if it doesn't exist already
    confdir = os.path.join(casebld, 'vicconf')
    if not os.path.isdir(confdir):
        os.makedirs(confdir)

    # copy input files config to
    src_file = os.path.join(coderoot, 'lnd/vic/vic/drivers/cesm/bld', config_file)
    dst_file = os.path.join(confdir, config_file)
    if not os.path.isfile(dst_file):
        shutil.copy(src_file, dst_file)
        os.chmod(dst_file, stat.S_IWUSR | stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)

    # parse the config file
    all_grids = read_config(os.path.join(confdir, config_file))

    # Get the config for the current LND_GRID
    try:
        grid_config = all_grids[grid]
    except KeyError:
        raise KeyError('Requested Grid "{0}" is not '
                       'defined in {1}'.format(grid, config_file))

    # copy VIC files to confdir
    for key in ['vic_global_param', 'vic_constants']:
        src_file = os.path.join(coderoot, 'lnd/vic/vic/drivers/cesm/bld', grid_config[key])
        dst_file = os.path.join(confdir, grid_config[key])
        if not os.path.isfile(dst_file):
            shutil.copy(src_file, dst_file)
            os.chmod(dst_file, stat.S_IWUSR | stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
        if key in grid_config:
            grid_config[key] = dst_file

    # copy Constants and Global Parameters to RUNDIR
    for filekey, header_txt in [('vic_constants', 'Constants'),
                                ('vic_global_param', 'Global Parameters')]:
        header = header_template.format(header_txt, caseid)
        dst_file = os.path.join(rundir, os.path.basename(grid_config[filekey]))

        # if file exists so add temporarily write permissions
        if os.path.isfile(dst_file):
            os.chmod(dst_file, stat.S_IWUSR)

        # copy file
        copy_clean_vic_config(grid_config[filekey], dst_file,
                              header=header, rundir=rundir, **grid_config)

        # update the grid config
        grid_config[filekey] = dst_file

        # change permissions to read only
        os.chmod(dst_file, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)

    # write input files list
    dst_file = os.path.join(casebld, 'vic.input_data_list')

    # if file exists so add temporarily write permissions
    if os.path.isfile(dst_file):
        os.chmod(dst_file, stat.S_IWUSR)

    write_input_data_list(grid_config, dst_file)
    os.chmod(dst_file, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)


def read_config(config_file):
    """
    Return a dictionary with subdictionaries of all configFile options/values
    """

    if not os.path.isfile(config_file):
        raise VIC_Error('Config File {0} does not exist'.format(config_file))

    config = SafeConfigParser()
    config.optionxform = str
    config.read(config_file)
    sections = config.sections()
    dict1 = {}
    for section in sections:
        options = config.options(section)
        dict2 = {}
        for option in options:
            dict2[option] = config.get(section, option)
        dict1[section] = dict2

    return dict1


def copy_clean_vic_config(src, dst, header=None, **kwargs):
    """Copy VIC style ASCII configuratoin file from src to dst

        remove comments and empty lines
    """
    with open(src, 'r') as fsrc:
        with open(dst, 'w') as fdst:
            lines = fsrc.readlines()
            if header is not None:
                fdst.write(header)
            for line in lines:
                line = line.format(**kwargs)
                line = os.path.expandvars(line.split('#', 1)[0].strip())
                if line:
                    fdst.write(line + '\n')


def write_input_data_list(files, fname):
    """Write standard CESM input data namelist"""
    with open(fname, 'w') as f:
        for k, v in files.items():
            line = '{0} = {1}\n'.format(k, os.path.expandvars(v))
            f.write(line)


if __name__ == "__main__":
    main()
